### ISSUE TITLE
Add Video Player

### ISSUE THREAD

**Issue by gsvarma** [DreamStarPro/mWebsite#22]
Let's add a video player for the website which plays video files stored in our [Content](https://github.com/DreamStarPro/mWebsite/tree/master/Content) folder.
Of course, there are no video files in it at the moment. So, feel free to add some dummy video files to test.

**Comment by vipasyan** [comment]
Please check branch Adding-video-player and suggest how to solve the below directory error
![capture](https://user-images.githubusercontent.com/34027054/53653927-c615a880-3c4c-11e9-9451-e8ed61007bad.JPG)

**Comment by gsvarma** [comment]
The **error** is due to missing of a filename in the path.

https://github.com/DreamStarPro/mWebsite/blob/4a2474d96822eff3bc42ffa442dbbae92b145077/Pages/content.html#L65

P.S. I suggest using videos from sites like [Pexels](https://videos.pexels.com/) which offer free stock footage, for testing your code.

**Comment by vipasyan** [comment]
Yeah, got it. Thank you.

**Comment by gsvarma** [comment]
#23
