### ISSUE TITLE
Image in Home page

### ISSUE THREAD

**Issue by vipasyan** [DreamStarPro/mWebsite#3]
Add image of Meher Baba on the home screen.

**Comment by vipasyan** [comment]
Requested Enhancement
![12](https://user-images.githubusercontent.com/34027054/42234262-4a21fdac-7ef4-11e8-86ef-33bbc35b65f7.jpg)

**Comment by gsvarma** [comment]
The requested enhancement is done. a9b8c8c37ac61de07eb84a6671609df02cbfb549
